---

- hosts: localhost
  tasks:
    - name: Install StrongSwan on Ubuntu
      ansible.builtin.include_tasks: "install/ubuntu.yml"
      when: ansible_os_family == 'Debian'
    - name: Install StrongSwan on Fedora
      ansible.builtin.include_tasks: "install/ubuntu.yml"
      when: ansible_os_family == 'RedHat'
